### ISSUE TITLE
API Key?

### ISSUE THREAD

**Issue by siara-cc** [plasma-umass/sqlwrite#1]
Hi, I think this is a great idea !!
When I tried this I am getting a message "You didn't provide an API key".  How do I provide it?
Also I don't have access to ChatGPT-4.  Does it work with GPT-3?

**Comment by emeryberger** [comment]
Thanks for your note. SQLwrite doesn't use GPT-4. I've added more instructions in the `README.md` file, and the latest version in the repo now has much nicer error handling. Will issue a new release momentarily!

**Comment by siara-cc** [comment]
Thanks for clarifying this!  I tried providing API key, now it says "You exceeded your current quota, please check your plan and billing details.".  Looks like it does not work with the free version :-)

**Comment by emeryberger** [comment]
It's not clear to me that there _is_ a free version. What model are you using? (SQLwrite is still by default using GPT-3.5-Turbo.)

**Comment by emeryberger** [comment]
As far as I am aware, the only "free" part is an initial $5 credit to your quota. Then you have to pay.

**Comment by siara-cc** [comment]
Lol you are right. There is no free version for the models except for the initial credit.  Just that I have forgotten that and got confused with the ChatGPT 3.5 which I am still getting for free. I apologize!
